namespace Hospital.Server.Entities.Response
{
    /// <summary>
    /// Response returned by POST /api/v1/PatientPortal/pay on successful payment.
    /// Contains all data needed to render the confirmation screen and send the
    /// confirmation e-mail to the patient.
    /// </summary>
    public class PaymentConfirmationResponse
    {
        /// <summary>
        /// Unique transaction number generated by the payment gateway.
        /// </summary>
        public string TransactionNumber { get; set; } = string.Empty;

        /// <summary>
        /// ID of the appointment that was paid.
        /// </summary>
        public long AppointmentId { get; set; }

        /// <summary>
        /// Full name of the attending doctor.
        /// </summary>
        public string DoctorName { get; set; } = string.Empty;

        /// <summary>
        /// Name of the medical specialty.
        /// </summary>
        public string SpecialtyName { get; set; } = string.Empty;

        /// <summary>
        /// Name of the branch / clinic where the appointment will take place.
        /// </summary>
        public string BranchName { get; set; } = string.Empty;

        /// <summary>
        /// Confirmed appointment date and time.
        /// </summary>
        public DateTime AppointmentDate { get; set; }

        /// <summary>
        /// Amount charged.
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// E-mail address of the patient (used to confirm where the receipt was sent).
        /// </summary>
        public string PatientEmail { get; set; } = string.Empty;
    }
}
