import type { InventoryMovementResponse } from "../../types/InventoryMovementResponse";
import type { TableColumnWithFilters } from "../../types/TableColumnWithFilters";
import { formatDateTime } from "../../utils/dateFormatter";
import { MovementTypeBadge } from "../badge/MovementTypeBadge";
import { InventoryMovementButton } from "../button/InventoryMovementButton";

export const InventoryMovementResponseColumns: TableColumnWithFilters<InventoryMovementResponse>[] =
  [
    {
      id: "createdAt",
      name: "Fecha/Hora",
      selector: (data) => formatDateTime(data.createdAt),
      sortable: true,
      wrap: true,
      omit: false,
      hasFilter: false,
    },
    {
      id: "movementType",
      name: "Tipo",
      cell: (data) => <MovementTypeBadge movementType={data.movementType} />,
      sortable: true,
      wrap: true,
      omit: false,
      hasFilter: true,
      filterField: (value) => (value ? `MovementType:eq:${value}` : ""),
    },
    {
      id: "medicine",
      name: "Medicamento",
      selector: (data) => data.medicine?.name ?? String(data.medicineId),
      sortable: true,
      wrap: true,
      omit: false,
      hasFilter: true,
      filterField: (value) => (value ? `Medicine.Name:like:${value}` : ""),
    },
    {
      id: "branch",
      name: "Sucursal",
      selector: (data) => data.branch?.name ?? String(data.branchId),
      sortable: true,
      wrap: true,
      omit: false,
      hasFilter: true,
      filterField: (value) => (value ? `Branch.Name:like:${value}` : ""),
    },
    {
      id: "quantity",
      name: "Cantidad",
      selector: (data) => data.quantity ?? 0,
      sortable: true,
      wrap: true,
      omit: false,
      hasFilter: false,
    },
    {
      id: "previousStock",
      name: "Stock Anterior",
      selector: (data) => data.previousStock ?? 0,
      sortable: true,
      wrap: true,
      omit: false,
      hasFilter: false,
    },
    {
      id: "newStock",
      name: "Stock Nuevo",
      selector: (data) => data.newStock ?? 0,
      sortable: true,
      wrap: true,
      omit: false,
      hasFilter: false,
    },
    {
      id: "totalCost",
      name: "Costo",
      selector: (data) => `Q ${(data.totalCost ?? 0).toFixed(2)}`,
      sortable: true,
      wrap: true,
      omit: false,
      hasFilter: false,
    },
    {
      id: "referenceNumber",
      name: "Referencia",
      selector: (data) => data.referenceNumber ?? "—",
      sortable: false,
      wrap: true,
      omit: false,
      hasFilter: true,
      filterField: (value) => (value ? `ReferenceNumber:like:${value}` : ""),
    },
    {
      id: "user",
      name: "Usuario",
      selector: (data) => data.user?.name ?? String(data.userId),
      sortable: true,
      wrap: true,
      omit: false,
      hasFilter: true,
      filterField: (value) => (value ? `User.Name:like:${value}` : ""),
    },
    {
      id: "actions",
      name: "Acciones",
      maxWidth: "100px",
      center: true,
      button: true,
      cell: (data) => <InventoryMovementButton data={data} />,
    },
  ];
