import type { TableColumnWithFilters } from "../../types/TableColumnWithFilters";
import type { VitalSignResponse } from "../../types/VitalSignResponse";
import { VitalSignButton } from "../button/VitalSignButton";
import { formatDateTime } from "../../utils/dateFormatter";

export const VitalSignResponseColumns: TableColumnWithFilters<VitalSignResponse>[] = [
  {
    id: "id",
    name: "ID",
    selector: (data) => data.id ?? "",
    sortable: true,
    wrap: true,
    omit: false,
    hasFilter: true,
    filterField: (value) => (value ? `Id:eq:${value}` : ""),
  },
  {
    id: "appointmentId",
    name: "Cita",
    selector: (data) => data.appointmentId ?? "",
    sortable: true,
    wrap: true,
    omit: false,
    hasFilter: true,
    filterField: (value) => (value ? `AppointmentId:eq:${value}` : ""),
  },
  {
    id: "bloodPressure",
    name: "Presión Arterial",
    selector: (data) => `${data.bloodPressureSystolic}/${data.bloodPressureDiastolic} mmHg`,
    sortable: false,
    wrap: true,
    omit: false,
    hasFilter: false,
  },
  {
    id: "temperature",
    name: "Temperatura",
    selector: (data) => `${data.temperature} °C`,
    sortable: true,
    wrap: true,
    omit: false,
    hasFilter: false,
  },
  {
    id: "heartRate",
    name: "Frec. Cardíaca",
    selector: (data) => `${data.heartRate} bpm`,
    sortable: true,
    wrap: true,
    omit: false,
    hasFilter: false,
  },
  {
    id: "weight",
    name: "Peso",
    selector: (data) => `${data.weight} kg`,
    sortable: true,
    wrap: true,
    omit: true,
    hasFilter: false,
  },
  {
    id: "height",
    name: "Altura",
    selector: (data) => `${data.height} cm`,
    sortable: true,
    wrap: true,
    omit: true,
    hasFilter: false,
  },
  {
    id: "isEmergency",
    name: "Emergencia",
    selector: (data) => (data.isEmergency ? "🚨 Sí" : "No"),
    sortable: false,
    wrap: true,
    omit: false,
    hasFilter: false,
  },
  {
    id: "actions",
    name: "Acciones",
    maxWidth: "100px",
    center: true,
    button: true,
    cell: (data) => <VitalSignButton data={data} />,
  },
  {
    id: "createdAt",
    name: "Creado",
    selector: (data) => formatDateTime(data.createdAt),
    sortable: true,
    maxWidth: "160px",
    omit: true,
  },
];
