namespace Hospital.Server.Entities.Request
{
    /// <summary>
    /// Request DTO for processing a patient payment via the portal.
    /// Standalone class — does NOT implement IRequest&lt;long&gt;.
    /// </summary>
    public class PatientPaymentRequest
    {
        /// <summary>
        /// ID of the appointment being paid.
        /// </summary>
        public long AppointmentId { get; set; }

        /// <summary>
        /// Amount to charge.
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// Payment method: 1 = Visa, 2 = Mastercard.
        /// </summary>
        public int PaymentMethod { get; set; }

        /// <summary>
        /// Payment type: 0 = Consulta.
        /// </summary>
        public int PaymentType { get; set; }

        /// <summary>
        /// Payment status: 0 = Pendiente.
        /// </summary>
        public int PaymentStatus { get; set; }

        /// <summary>
        /// Date and time the payment was initiated.
        /// </summary>
        public DateTime PaymentDate { get; set; }

        /// <summary>
        /// Last four digits of the card used (never the full number).
        /// </summary>
        public string CardLastFourDigits { get; set; } = string.Empty;

        /// <summary>
        /// UUID v4 idempotency key generated by the frontend to prevent duplicate charges.
        /// </summary>
        public string IdempotencyKey { get; set; } = string.Empty;
    }
}
